name: Close Jira Issue on GitHub Issue Close
on:
  issues:
    types: [closed]

jobs:
  close_jira:
    runs-on: ubuntu-latest
    steps:
      - name: Jira Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

      - name: Extract Jira Issue Key from Title
        id: extract
        run: |
          TITLE="${{ github.event.issue.title }}"
          KEY=$(echo "$TITLE" | grep -oE '[A-Z]+-[0-9]+')
          echo "JIRA_KEY=$KEY" >> $GITHUB_ENV

      - name: Transition Jira Issue to Done
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ env.JIRA_KEY }}
          transition: "Done"
